### ISSUE TITLE
Zarvis service is down , unable to test deployment

### ISSUE THREAD

**Issue by syprasha1994** [zarvis-ai/community#4]

**Comment by edwin-zvs** [comment]
Could you share error message you see?

**Comment by syprasha1994** [comment]
Hello edward,
Kindly find the error message attached

**Comment by syprasha1994** [comment]
![image](https://user-images.githubusercontent.com/61225226/74859156-7acc3c80-536c-11ea-8b94-2b869ce3fc06.png)

**Comment by edwin-zvs** [comment]
We were temporary disabled the new project deployments. Existing deployments were working without interruptions. But now, new project deployments are enabled again. Thanks @syprasha1994 for interest to the service.
