### ISSUE TITLE
Zarvis development: we are engineering team doing some R&D on ZARVIS, if we need to extend the framework or develop on that then how do we approach it or what is the enterprise extensions required, can you kindly help us get some guidance on this or where to look for the reference documents for the development

### ISSUE THREAD

**Issue by syprasha1994** [zarvis-ai/community#5]

**Comment by edwin-zvs** [comment]
Please share little more about what 'extend the framework' and 'enterprise extensions' means. Could you give an example what are you trying to achieve?

**Comment by syprasha1994** [comment]
we needed to deploy few sample application and test zarvis framework,  if there is any requirement for us to move on cloud , just wanted to explore zarvis , also we found a developer tab on zarvis , needed to explore it more.
Note: zarvis was down again when i tried testing

**Comment by edwin-zvs** [comment]
Zarvis is rapidly improving and you may see 'renewing service' message time to time on web console. Apologies for inconvenience. However, deployed services are always up and running regardless of 'renewing service' message you see on the web console.

Regarding requirement to getting started, check https://docs.zarvis.ai/getting_started/index.html.
Also check https://docs.zarvis.ai/how_it_works/namespace.html to see what kind of kubernetes resources we support today.
