### ISSUE TITLE
Setting up custom domain never pass verify ownership

### ISSUE THREAD

**Issue by ricardogouveia3** [zarvis-ai/community#8]
Hey guys,

I'm trying to use my custon domain with my express app on ZARVIS but when I try to get the "Verify Ownership" step it just stays loading forever.

I've set up two CNAME on my godaddy domain account: 'dev-api' and 'api' both pointing to my production url pointed on ZARVIS page. I'm not sure this is the right thing to do since the only domain I would like to use with ZARVIS is api.mydomain.me, but as requested by the verification step, I had to have 2 CNAMES, and I can't have 2 identical CNAMES on godaddy.

I'm not expert on this domain configurations, so could you guys help me on this? I could not find any docs for it on ZARVIS...

**Comment by edwin-zvs** [comment]
Adding new custom domain feature has some problem at the moment. (existing custom domain is okay)
Let us working on the fix and come back to you.

regarding 2 CNAME, they're look like

<YOUR_DOMAIN> CNAME <YOUR_PROJECT_DOMAIN_IN_ZARVIS>
<ACME_CHALLENGE_DOMAIN> CNAME <ACME_CHALLENGE_DATA>

Once we fix the issue, custom domain screen will shows guideline.

**Comment by edwin-zvs** [comment]
@ricardogouveia3 We just fixed the problem and you'll see CNAME guide line in "Verify ownership" step.
Apologies for inconvenience and let us know if you still experience the problem.

Thanks

**Comment by ricardogouveia3** [comment]
Just configured my custom domain. Thanks!
